version: '3.7'

services:
  app:
    image: node:17.3.0-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
      - '9229:9229'
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: PokemonDatabase
      MYSQL_DB: pokemon

  mysql:
    image: mysql:5.7
    volumes:
      - pokemon-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: PokemonDatabase
      MYSQL_DATABASE: pokemon

volumes:
  pokemon-mysql-data:
