version: "3.7"

services:
  app:
    image: node:16.13.1-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: PokemonDatabase
      MYSQL_DB: pokemon
  
  mysql:
    image: mysql:5.7
    volumes:
      - pokemon-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: PokemonDatabase
      MYSQL_DATABASE: pokemon

volumes:
  pokemon-mysql-data: